### ISSUE TITLE
Bottom / Bot

### ISSUE THREAD

**Issue by rougier** [jonathanchu/emacs-powerline#3]
Woudl that be possible to write "Bot" instead of "Bottom" when at the end of buffer ?
("Bottom" is too big realtive to allocated space)

Nicolas

**Comment by jonathanchu** [comment]
This is a good concern, as it brings up a bigger issue.  Depending on what info is displayed in the mode line, the bar will be of variable length.  Do you have a lot of total characters combined for your filename, major mode, minor modes, version control, line/column number?  If so, you'll run into this issue.

For example, this is ~550px width.  If any of the sections or modes have any more characters, it will cut off the "Bottom" buffer space.

![emacs-powerline screenshot](http://i.imgur.com/DSYqN.png)

I'm inclined to leave it as-is because if you just make your Emacs window wider, the problem goes away.  There is a _reasonable_ minimum width we should accommodate though.  Suggestions are welcomed for this!

**Comment by rougier** [comment]
Yep, you're right.
My concern was mainly to have "Bot" because "Top" or "33%" are 3 characters wide. And I nver find the way to get "Bot" instead of "Bottom".

Feel free to close the issue.

**Comment by jonathanchu** [comment]
Thanks for the feedback! :smiley:
